### ISSUE TITLE
import failure with SyntaxError: invalid syntax in simuOpt after source install on python 3.6

### ISSUE THREAD

**Issue by ashander** [BoPeng/simuPOP#16]
I've installed from source on Ubuntu 16.10 with python 3.6. Here's what I did:

```sh
$ git clone https://github.com/BoPeng/simuPOP.git
$ cd simuPOP
$ conda create -n simuPOP ipython
$ source activate simuPOP
$ python setup.py install
````
after this, importing `simuPOP` fails
```sh
 $ python -Ec 'import simuPOP'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jaime/miniconda3/envs/simuPOP/lib/python3.6/site-packages/simuPOP-1.1.8svn-py3.6-linux-x86_64.egg/simuPOP/__init__.py", line 305, in <module>
    from simuOpt import simuOptions
  File "/home/jaime/simuPOP/simuOpt.py", line 922
    except Exception,e:
                    ^
SyntaxError: invalid syntax
```

Environment info below

```
$ python --version
Python 3.6.0 :: Continuum Analytics, Inc.
 $ conda list
# packages in environment at /home/jaime/miniconda3/envs/simuPOP:
#
decorator                 4.0.10                   py36_1  
ipython                   5.1.0                    py36_0  
ipython_genutils          0.1.0                    py36_0  
openssl                   1.0.2j                        0  
path.py                   9.0.1                    py36_0  
pexpect                   4.0.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pip                       9.0.1                    py36_1  
prompt_toolkit            1.0.9                    py36_0  
ptyprocess                0.5.1                    py36_0  
pygments                  2.1.3                    py36_0  
python                    3.6.0                         0  
readline                  6.2                           2  
setuptools                27.2.0                   py36_0  
simplegeneric             0.8.1                    py36_1  
simuPOP                   1.1.8svn                  <pip>
six                       1.10.0                   py36_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
traitlets                 4.3.1                    py36_0  
wcwidth                   0.1.7                    py36_0  
wheel                     0.29.0                   py36_0  
xz                        5.2.2                         1  
zlib                      1.2.8                         3  
```

**Comment by BoPeng** [comment]
This is because you are running the command from the simuPOP source directory, so it imported `/home/jaime/projects/dtpva/simuPOP/simuOpt.py`, not the `simuOpt.py` under `/home/jaime/miniconda3/envs/simuPOP/lib/python3.6/site-packages/simuPOP-1.1.8svn-py3.6-linux-x86_64.egg/`. The latter should be translated to python3 syntax during installation.

**Comment by ashander** [comment]
Ah! A silly mistake. Thanks. But: after moving back out of the `simuPOP` directory, I still have an error . 

Note that when running `python setup.py install` I get the warning/message `Failed to pre-compile boost headers: Failed to pre-compile boost headers` perhaps this could be related? 

```sh
$ python -c 'import simuPOP'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jaime/miniconda3/envs/simuPOP/lib/python3.6/site-packages/simuPOP-1.1.8svn-py3.6-linux-x86_64.egg/simuPOP/__init__.py", line 323, in <module>
    from simuPOP.simuPOP_std import *
  File "/home/jaime/miniconda3/envs/simuPOP/lib/python3.6/site-packages/simuPOP-1.1.8svn-py3.6-linux-x86_64.egg/simuPOP/simuPOP_std.py", line 32, in <module>
    _simuPOP_std = swig_import_helper()
  File "/home/jaime/miniconda3/envs/simuPOP/lib/python3.6/site-packages/simuPOP-1.1.8svn-py3.6-linux-x86_64.egg/simuPOP/simuPOP_std.py", line 28, in swig_import_helper
    _mod = imp.load_module('_simuPOP_std', fp, pathname, description)
  File "/home/jaime/miniconda3/envs/simuPOP/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/jaime/miniconda3/envs/simuPOP/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: 
/home/jaime/miniconda3/envs/simuPOP/lib/python3.6/site-packages/simuPOP-1.1.8svn-py3.6-linux-x86_64.egg/simuPOP/_simuPOP_std.cpython-36m-x86_64-linux-gnu.so: 
undefined symbol: _ZTIN5boost7archive6detail14basic_iarchiveE
```
More env information (I have all the sys reqs listed at http://simupop.sourceforge.net/Main/Download ):
```sh
 $ dpkg -s libboost-dev |grep 'Ver'                                                                                                                                                  
Version: 1.61.0.2
 $ dpkg -s zlib1g-dev |grep 'Ver'                                                                                                                                                    
Version: 1:1.2.8.dfsg-2ubuntu5
 $ dpkg -s  libstdc++6 |grep 'Ver'
Version: 6.2.0-5ubuntu12
 $ locate Python.h
/usr/include/python2.7/Python.h
```

**Comment by BoPeng** [comment]
Could you list the error message for compiling boost?

**Comment by ashander** [comment]
I'm not sure how to get the full message. Here's the first few lines of output from install with `--verbose` specified

```sh
 $ python setup.py install --verbose
Failed to pre-compile boost headers: Failed to pre-compile boost headers
Building static libraries
/home/jaime/miniconda3/envs/simuPOP/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/dist.py:340: UserWarning: The version specified ('1.1.8svn') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
running install
running bdist_egg
running egg_info
writing simuPOP.egg-info/PKG-INFO
writing dependency_links to simuPOP.egg-info/dependency_links.txt
writing requirements to simuPOP.egg-info/requires.txt
writing top-level names to simuPOP.egg-info/top_level.txt
reading manifest file 'simuPOP.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'TODO'
```

**Comment by BoPeng** [comment]
This is not it. I need message for compiling boost.

**Comment by ashander** [comment]
Gotcha. Do you mean `cd` into boost directory and run a manual install as [detailed in Boost docs](http://www.boost.org/doc/libs/1_41_0/more/getting_started/unix-variants.html)?

If so, I've done that and am currently compiling. But: I had to `tar -xzf boost_1_49_0` in the root simuPOP directory first, because apparently `python setup.py install` did not unzip `boost_1_49_0/boostrap.sh` and friends.

If not, do you know how can I get the compile messages out of `setup.py`? Thx

**Comment by BoPeng** [comment]
Ohmm, actually the `headers: Failed to pre-compile boost headers` message is expected and the setup process must have been successful. I will find an ubuntu machine and try to reproduce your problem soon (ish, like one or two days).

**Comment by BoPeng** [comment]
Since you have system boost, 
```
 $ dpkg -s libboost-dev |grep 'Ver'                                                                                                                                                  
Version: 1.61.0.2
```

simuPOP might be using the newer version of boost that is not compatible. Could you remove the system boost library and try again? In this case simuPOP will automatically download a known-to-work version of boost (1.49) and embed it.

**Comment by ashander** [comment]
Ah. The system vs embedded boost is a good idea. I will see if it works and report back.

By the way: is the `Dockerfile` used to build [the mdabioinfo/simupop image on dockerhub]( https://hub.docker.com/r/mdabioinfo/simupop/) available somewhere?

**Comment by BoPeng** [comment]
https://github.com/BoPeng/simuPOP/blob/master/development/docker/Dockerfile

**Comment by ashander** [comment]
Great. I didn't notice `development/` till now.

Update: I removed the system boost and rebuilt and it works. Thanks!

**Comment by BoPeng** [comment]
If you get a chance, could you check if you can reproduce #7 on your ubuntu setup? We are having trouble reproducing this bug so it might have been fixed somewhere, perhaps even not by simuPOP.
