### ISSUE TITLE
simuPOP unittest print error message for assertRaises

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/simuPOP#22]
`assertRaises` should silently report success if an exception of the specified type is raised. Strangely, right now in simuPOP's unittest all error messages are printed even if the tests pass.

To reproduce:

```
$ python test_17_utils.py TestUtils.testExportFStat
Traceback (most recent call last):
  File "/Users/bpeng1/bin/anaconda/lib/python3.5/site-packages/simuPOP-1.1.8svn-py3.5-macosx-10.6-x86_64.egg/simuPOP/utils.py", line 3097, in _export
    self._determineSubPops(pop), self.infoFields, gui=self.gui)
  File "/Users/bpeng1/bin/anaconda/lib/python3.5/site-packages/simuPOP-1.1.8svn-py3.5-macosx-10.6-x86_64.egg/simuPOP/utils.py", line 1925, in export
    raise ValueError('Parameter lociNames, if specified, should give all %d loci a name' % pop.totNumLoci())
ValueError: Parameter lociNames, if specified, should give all 6 loci a name
.
----------------------------------------------------------------------
Ran 1 test in 0.011s

OK
```

**Comment by BoPeng** [comment]
OK, these functions are routed through the C++ core by `PyOperator` so the error message was caught and printed there before the exception was thrown to the Python level.
