### ISSUE TITLE
Can ordering of parents chosen by SequentialParentsChooser be changed?

### ISSUE THREAD

**Issue by ashander** [BoPeng/simuPOP#32]
Is there any (built-in) way to make a sequential chooser provide parents from VSPs, in order of the VSPs? That is if parents 1 and 2 are in vsp 0 and parents 3 and 4 are in vsp 1, can I somehow make parents 3 and 4 be chosen before parents 1 and 2? 

I thought that the order in which VSPs are specified to the `subPops=` argument of a `MatingScheme` might do this, but the example below shows it has no effect on the order in which parents are chosen from by a `SequentialParentChooser`. 

Thanks,

```py
def test_sequence(vsp_ranges, sub_pop_spec, tgt_mother_order):
    '''Ordering is always the same as Population.individuals(subpop)'''
    info_vals = [1, 2, 3, 4, 5, 6, 7, 8, 9]
    size = [3, 6]
    sex_init = [sim.MALE, sim.FEMALE, sim.FEMALE]
    class Reporter():
        def __init__(self):
            self.mom_order = []

        def __call__(self, dad, mom, off):
            self.mom_order.append(int(mom.ind_id))
            return True

    pop = sim.Population(size,
                         infoFields=['a', 'ind_id', 'father_id', 'mother_id'],
                         ancGen=-1,)
    sim.initInfo(pop, infoFields='a', values=info_vals)
    sim.initSex(pop, sex=sex_init)
    pop.setVirtualSplitter(sim.InfoSplitter(field='a', ranges=vsp_ranges))

    report = Reporter()
    pop.evolve(
        initOps=[sim.IdTagger(), sim.Dumper()],
        matingScheme=sim.HomoMating(chooser=sim.CombinedParentsChooser(
            sim.RandomParentChooser(replacement=True, sexChoice=sim.MALE_ONLY),
            sim.SequentialParentChooser(sexChoice=sim.FEMALE_ONLY)
        ),
            generator=sim.OffspringGenerator(
                ops=[sim.PedigreeTagger(),
                     sim.IdTagger(),
                     sim.PyOperator(report)],
                numOffspring=1),
            subPopSize=[2, 4],
            subPops=sub_pop_spec),
        postOps=[sim.Dumper()],
        gen=1)
    actual_mother_order =[int(pop.indByID(ind).a) for ind in report.mom_order]
    assert tgt_mother_order == actual_mother_order, "target {} missed. actual: {}".format(tgt_mother_order,
                                                                                          actual_mother_order)


if __name__ == '__main__':
    # phys pop1: vsp1, phys pop2: vsp2, vsp4
    test_sequence([[1, 4], [4, 7], [7, 10]],
                  [(sim.ALL_AVAIL, 0), (sim.ALL_AVAIL, 1), (sim.ALL_AVAIL, 2)],
                  [2, 3, 5, 6, 8, 9])
    # if vsps affect ordering of parents from sequential chooser,
    # this should work too
    test_sequence([[1, 4], [4, 7], [7, 10]],
                  [(sim.ALL_AVAIL, 0), (sim.ALL_AVAIL, 2), (sim.ALL_AVAIL, 1)],
                  [2, 3, 8, 9, 5, 6])
```
which gives output

```sh
Traceback (most recent call last):
  File "sequential_q.py", line 58, in <module>
    [2, 3, 8, 9, 5, 6])
  File "sequential_q.py", line 46, in test_sequence
    actual_mother_order)
AssertionError: target [2, 3, 8, 9, 5, 6] missed. actual: [2, 3, 5, 6, 8, 9]
```

**Comment by BoPeng** [comment]
Did you notice in the documentation

class HomoMating
A homogeneous mating scheme that uses a parent chooser to choose parents from a parental generation, and an offspring generator to generate offspring from chosen parents. It can be either used directly, or within a heterogeneous mating scheme. **In the latter case, it can be applied to a (virtual) subpopulation**.

That is to say `subPops` is ignored if `HomoMating` is used by itself.

**Comment by ashander** [comment]
I missed it, but upon rereading the class docs for `HomoMating` it's clear that the argument only works within a `HeteroMating` scheme. The changes below work as expected.

```sh  
 32  matingScheme=sim.HeteroMating([sim.HomoMating(chooser=sim.CombinedParentsChooser(                                                                                                                      
 33             sim.RandomParentChooser(replacement=True, sexChoice=sim.MALE_ONLY),                                                                                                                                
 34             sim.SequentialParentChooser(sexChoice=sim.FEMALE_ONLY)                                                                                                                                             
 35         ),                                                                                                                                                                                                     
 36             generator=sim.OffspringGenerator(                                                                                                                                                                  
 37                 ops=[sim.PedigreeTagger(),                                                                                                                                                                     
 38                      sim.IdTagger(),                                                                                                                                                                           
 39                      sim.PyOperator(report)],                                                                                                                                                                  
 40                 numOffspring=1),                                                                                                                                                                               
 41             subPops=sub_pop_spec)],                                                                                                                                                                            
 42             subPopSize=[2, 4]),                                                   
```
