### ISSUE TITLE
syntax error: simuPOP import

### ISSUE THREAD

**Issue by dinhe878** [BoPeng/simuPOP#64]
Dear developer,

I installed simuPOP-1.1.9 with pip on my Mac. I use python 2.7 (anaconda2). Installation was fine but I got syntax error when import the module:

Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:05) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import simuPOP
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ding/anaconda2/lib/python2.7/site-packages/simuPOP/__init__.py", line 323, in <module>
    from simuPOP.simuPOP_std import *
  File "/Users/ding/anaconda2/lib/python2.7/site-packages/simuPOP/simuPOP_std.py", line 211
    def __init__(self, msg: 'string const &'):
                          ^
SyntaxError: invalid syntax

Any help would be appreciated!

**Comment by BoPeng** [comment]
Simupop 1.1.9 only works for python 3.  Please check the installation instructions if you have to use python 2.7.

**Comment by dinhe878** [comment]
Thanks! I now created a new conda environment and installed python3.7.1 as well as simupop-1.1.9.
